### ISSUE TITLE
Request for Auto-Formatting of Generated Code

### ISSUE THREAD

**Issue by K9i-0** [slang-i18n/slang#184]
The code generated by slang currently shows differences when formatted with `dart format .`.

I want it to auto-format like in packages using source_gen, like freezed. They use DartFormatter from the dart_style package. Using DartFormatter the same way should work.
https://pub.dev/packages/dart_style#using-the-dart_style-api

Similar to Issue #163

**Comment by Tienisto** [comment]
Unfortunately, `slang` is a direct dependency and not a dev dependency. This will also not change in the near future because [Translation Overrides](https://github.com/slang-i18n/slang#-translation-overrides) reuses most logic from the generator.

A trade-off would be to add this to `slang_build_runner` but this will make the generated code of `dart run slang` and `dart run build_runner build` different / inconsistent.

**Comment by Tienisto** [comment]
Added `format` config in `v4.1.0`
